### ISSUE TITLE
Nintendo world championships 1990

### ISSUE THREAD

**Issue by GB-CG** [FIX94/nes-continue-patches#2]
I like to look at the title screen and press Start on the first controller port instead of the second like it normally does.
I know there's a patch for this, but it skips the title screen instantly.

**Comment by FIX94** [comment]
just had a quick 5 minute google and found this:
http://www.romhacking.net/forum/index.php?topic=14115.0
I assume thats what you want right? ;)

**Comment by GB-CG** [comment]
Yes please :) I remember that thread a while back.

**Comment by FIX94** [comment]
I guess you're not too comfortable to do hex edits? ;) Anyways I just applied those listed in that thread and they work just fine, wont upload this .ips file to the main repo since I did not create this patch after all.
[Nintendo World Championships 1990 (U) (P1 Start Hack).zip](https://github.com/FIX94/nes-various-patches/files/1908433/Nintendo.World.Championships.1990.U.P1.Start.Hack.zip)
